name: mi_card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - img/

  fonts:
    - family: SamimBold
      fonts:
        - asset: fonts/Samim-Bold-FD-WOL-1.ttf
    - family: Samimr
      fonts:
        - asset: fonts/Samim.ttf
    - family: Antapani
      fonts:
        - asset: fonts/Antapani-ExtraBold.otf


